const events = [
{type:'cosmic',context:true,date:'~13.8 billion years ago',title:'Universe begins',summary:'The Universe begins expanding from an extremely hot, dense early state.',why:'This creates the physical setting from which stars, planets, chemistry and eventually life become possible.',flow:'Universe → stars → heavier elements',details:['Hydrogen and helium dominate the earliest matter. Later generations of stars manufacture many of the heavier elements needed for rocky planets and life.']},
{type:'cosmic',context:true,date:'~13.6–13.0 billion years ago',title:'First stars and galaxies',summary:'Stars ignite; stellar fusion and explosions create and disperse heavier elements.',why:'Carbon, oxygen, nitrogen, silicon, iron and other ingredients of planets and life are forged through stellar evolution.',flow:'Stars make the ingredients → later solar systems',details:['This is the chemical bridge between the early Universe and the material that eventually becomes Earth and living organisms.']},
{type:'cosmic',context:true,date:'~4.6 billion years ago',title:'Sun and Solar System form',summary:'A cloud of gas and dust collapses. The Sun forms at the center while the surrounding disk produces planets.',why:'Material inherited from earlier stars becomes organized into our Solar System.',flow:'Solar nebula → Sun + planets',details:['Dust grains collide and grow into planetesimals and eventually planets. Earth forms in the inner rocky region of this disk.']},
{type:'earth',context:true,date:'~4.54 billion years ago',title:'Earth forms',summary:'Rocky material in the inner Solar System accretes into the young Earth.',why:'Earth becomes the planetary setting for the biological story.',flow:'Young Earth → cooling crust and oceans',details:['Early Earth was geologically violent and chemically very different from the modern planet.']},
{type:'earth',context:true,date:'~4.5 billion years ago',title:'Moon forms',summary:'The leading model involves a giant impact early in Earth history followed by accretion of orbiting debris.',why:'The Moon becomes a major part of Earth’s long-term planetary history.',details:['The exact details of the giant-impact process continue to be refined, but a major early collision remains the leading framework.']},
{type:'earth',context:true,date:'By ~4.4 billion years ago',title:'Early crust and liquid water',summary:'Ancient minerals indicate that crust and liquid water existed surprisingly early.',why:'Liquid water provides an important environment for prebiotic chemistry and early life.',details:['Zircon minerals preserve chemical clues that liquid water and differentiated crust existed by this time.']},
{type:'life',date:'Perhaps ~4.3–4.2 billion years ago (?)',title:'Origin of life',major:true,summary:'Prebiotic chemistry crossed the threshold into evolving biological systems. Exactly how, where and when remains unknown.',why:'This is the beginning of biology, before the last common ancestor of modern cellular life.',uncertainty:'Highly uncertain. The date is shown only to preserve chronological perspective.',flow:'Prebiotic chemistry ? → early evolving systems',details:['What Is Life? Before we can explore the Tree of Life, we first need to answer a simple question: What is life?','A simple scientific definition is: “Life is a self-maintaining system that uses energy, responds to its environment, reproduces, and has the capacity to evolve.”','Scientists do not have one universally accepted definition of life, but they generally agree that all living organisms share a common set of characteristics. A simple way to remember these characteristics is with the mnemonic HORGASM.','H – Homeostasis: Maintains a stable internal environment.','O – Organization: Is composed of one or more cells, the basic units of life.','R – Reproduction: Produces new organisms and passes genetic information to the next generation.','G – Growth: Increases in size and develops throughout its life cycle.','A – Adaptation: Populations evolve over generations, improving their ability to survive and reproduce.','S – Response to Stimuli: Detects and responds to changes in the environment.','M – Metabolism: Obtains, transforms, and uses energy and matter to build, maintain, and power the organism.']},
{type:'life',date:'Perhaps ~4.25–4.2 Ga (?)',title:'FUCA-type stage (?)',summary:'FUCA is a proposed label for a very early ancestral stage near the emergence of the genetic code and cellular life.',why:'It separates the hypothetical earliest shared biological ancestry from LUCA—the last shared ancestor of living cellular lineages.',uncertainty:'FUCA is a hypothetical concept, not a securely dated organism or fossil.',flow:'Early evolution → LUCA',details:['FUCA means “First Universal Common Ancestor” in this teaching framework.','Unlike LUCA, FUCA cannot be reconstructed with comparable confidence from genes shared by living organisms.','There may have been a long population-level transition rather than one single first cell.']},
{type:'life',date:'~4.2 billion years ago (estimate)',title:'LUCA — Last Universal Common Ancestor',major:true,summary:'The ancestral population from which all cellular life alive today ultimately descends. LUCA was not the first life.',why:'LUCA is the first major anchor for reconstructing the Tree of Life.',flow:'LUCA → Bacteria + Archaea',details:['Likely had DNA and RNA.','Used the universal genetic code, ribosomes and protein synthesis.','Used ATP-based energy metabolism and ion gradients.','Had basic metabolic pathways and reproduction.','Did NOT have a nucleus, mitochondria or chloroplasts.']},
{type:'life',date:'Perhaps ~4.1–3.5 billion years ago',title:'The Great Split — Bacteria and Archaea',major:true,summary:'Descendants of the universal ancestral population diverge into the two fundamental prokaryotic domains: Bacteria and Archaea.',why:'Both lineages survive to the present, and both later contribute crucial pieces to the eukaryotic story.',uncertainty:'The deepest split is extremely difficult to date; this broad range is for perspective.',flow:'Bacteria ← ancestral split → Archaea — BOTH CONTINUE TO TODAY',details:['Bacteria commonly have ester-linked membrane lipids and cell walls containing peptidoglycan.','Archaea have ether-linked membrane lipids, lack peptidoglycan, and have information-processing machinery with important similarities to eukaryotes.','Modern bacterial examples include cyanobacteria, E. coli, Bacillus and Streptococcus.','Modern archaeal examples include methanogens, halophiles, thermophiles, ammonia-oxidizers and Asgard archaea.','“Prokaryote” is a descriptive term for cells without a nucleus; it includes Bacteria and Archaea but is not itself a domain.']},
{type:'life',date:'By ~2.7 billion years ago; possibly earlier',title:'Cyanobacteria harness sunlight',major:true,summary:'Cyanobacteria use oxygenic photosynthesis: sunlight powers the production of energy-rich organic molecules, with oxygen released as a by-product.',why:'Life begins transforming the entire planet. Cyanobacteria also remain a living bacterial lineage today.',uncertainty:'Oxygenic photosynthesis predates the Great Oxidation Event; its exact origin is uncertain.',flow:'☀ Sunlight → Cyanobacteria → photosynthesis → O₂ waste',details:['Photosynthesis stores captured light energy in chemical bonds.','Using water as an electron donor releases molecular oxygen (O₂).','At first, much of that oxygen reacts with reduced iron, volcanic gases and other oxygen sinks instead of accumulating in the atmosphere.','Cyanobacteria do not disappear later: modern cyanobacteria still exist today.']},
{type:'earth',date:'~2.45–2.3 billion years ago',title:'Great Oxidation Event — oxygen changes the planet',major:true,summary:'Oxygen produced biologically begins to persist in the atmosphere and surface environments.',why:'Oxygen is toxic to many anaerobic organisms, but it also creates a powerful new opportunity for aerobic respiration.',flow:'Cyanobacterial O₂ → planetary oxygenation → new metabolic opportunity',details:['Before the GOE, atmospheric O₂ was extremely low compared with today.','Today O₂ is about 21% of the atmosphere.','There is no single secure “peak oxygen percentage” for the GOE; estimates remain debated.','The key teaching point is the transition from an essentially oxygen-poor atmosphere to one with persistent free oxygen.']},
{type:'life',date:'Before mitochondrial endosymbiosis; widespread as O₂ niches expand',title:'Aerobic respiration exploits oxygen',summary:'Some bacteria use oxygen as the final electron acceptor in respiration, allowing efficient extraction of usable energy from organic molecules.',why:'This metabolic capability sets the stage for the bacterial partner that becomes the mitochondrion.',flow:'Organic molecules + O₂ → efficient ATP production',details:['Life needs usable energy to run metabolism.','Aerobic respiration does not mean oxygen itself is “energy”; oxygen enables a highly effective electron-transport process that helps cells make ATP.','The alphaproteobacterial ancestor of mitochondria already possessed aerobic metabolic machinery before becoming an organelle.']},
{type:'life',date:'~2.37–1.80 billion years ago (broad estimate)',title:'Mitochondrial endosymbiosis — the energy partnership',major:true,summary:'An archaeal host related to the Asgard lineage forms a permanent partnership with an alphaproteobacterial relative capable of aerobic respiration.',why:'The bacterial partner becomes the MITOCHONDRION—an internal ATP-producing system central to the eukaryotic lineage.',uncertainty:'The exact date and sequence of eukaryogenesis remain debated.',flow:'Archaeal host + aerobic alphaproteobacterium → MITOCHONDRION → eukaryotic lineage',details:['This event occurred after oxygenic photosynthesis and the Great Oxidation Event, fitting the larger energy story.','Evidence for bacterial ancestry includes mitochondrial DNA, bacterial-type ribosomes, a double membrane, division by fission and phylogenetic affinity to Alphaproteobacteria.','Most mitochondrial genes were later lost or transferred to the host nucleus.','Mitochondria make ATP through oxidative phosphorylation, using oxygen indirectly as the final electron acceptor of the respiratory chain.','For clarity, this app reserves “primary endosymbiosis” for plastid/chloroplast origin.']},
{type:'life',date:'~1.80–1.67 billion years ago (estimate)',title:'LECA — Last Eukaryotic Common Ancestor',major:true,summary:'The ancestral population from which all living eukaryotic lineages descend. LECA was not the first eukaryote.',why:'By LECA, the core architecture of the modern eukaryotic cell—including mitochondria—was already highly developed.',flow:'LECA → many eukaryotic lineages',details:['Likely had mitochondria.','Had a nucleus and linear chromosomes.','Had a complex cytoskeleton and internal membrane systems.','Used vesicle trafficking and mitosis.','Probably had meiosis and sexual reproduction.','Had flagellar/ciliary machinery.']},
{type:'life',date:'Perhaps ~1.8–1.5 billion years ago',title:'The Tree expands — selected eukaryotic pathways',major:true,summary:'Eukaryotes diversify into many lineages. For our story we follow three selected pathways while many other eukaryotic lineages continue independently.',why:'This keeps the story understandable without implying that eukaryotes had only three branches.',flow:'Path 1 Animals/Fungi • Path 2 Red/Green Algae + Plants • Path 3 Brown Algae + Kelp',branches:[['Pathway 1','Animals & fungi → later humans'],['Pathway 2','Primary plastid → red algae + green algae → plants'],['Other eukaryotes','Many unicellular lineages continue → TODAY']],details:['The three pathways are teaching routes through a much larger eukaryotic tree.','Modern unicellular eukaryotes include amoebae, ciliates, dinoflagellates, many flagellates and numerous other groups.','Pathway 3 later receives a red-algal contribution from Pathway 2 through secondary endosymbiosis.']},
{type:'life',date:'Perhaps ~1.6–1.0 billion years ago',title:'Pathway 2 — primary endosymbiosis',major:true,summary:'A mitochondria-containing eukaryote engulfs a cyanobacterium. Instead of being digested, the cyanobacterium becomes permanently integrated.',why:'The cyanobacterial partner becomes the PRIMARY PLASTID—the ancestor of chloroplasts.',uncertainty:'The exact timing of primary plastid origin remains uncertain.',flow:'Eukaryote + Cyanobacterium → PRIMARY ENDOSYMBIOSIS → CHLOROPLAST',details:['Why “primary”? The engulfed partner is a bacterium—a cyanobacterium—not another eukaryotic alga.','Chloroplast evidence for cyanobacterial ancestry includes plastid DNA, bacterial-type ribosomes, division by fission and membrane architecture.','The host already had mitochondria, so photosynthetic eukaryotes combine two bacterial-derived energy systems: mitochondria and plastids.']},
{type:'life',date:'By ~1.05 billion years ago',title:'Pathway 2 branches — red algae and green algae',major:true,summary:'The primary-plastid lineage diversifies into red-algal and green-algal lineages. Both continue independently to the present.',why:'The green lineage later gives rise to land plants; a red-algal lineage later contributes to the brown-algal story without red algae disappearing.',uncertainty:'Accepted fossils establish red algae by ~1.05 Ga; the lineages themselves may be older.',flow:'CHLOROPLAST → 🔴 Red algae → TODAY  |  🟢 Green algae → TODAY + land plants',details:['Red and green algae are separate evolutionary lineages, not stages of one another.','Modern red algae continue today.','Modern green algae continue today.','A branch of the green lineage gives rise to land plants.','A red-algal lineage later participates in secondary endosymbiosis, while other red algae continue independently.']},
{type:'life',date:'Perhaps ~1.7–1.3 billion years ago (?)',title:'Pathway 3 begins — secondary endosymbiosis',major:true,summary:'Another eukaryotic lineage engulfs a red alga from Pathway 2—an alga that already contains a chloroplast descended from cyanobacteria.',why:'The red alga contributes its photosynthetic plastid to the lineage that ultimately gives rise to brown algae. Red algae themselves continue independently.',uncertainty:'The big-picture red-algal ancestry of the plastid is well supported, but the exact ancient route, number of transfers and timing remain debated.',flow:'Another eukaryote + 🔴 red alga [with chloroplast] → SECONDARY ENDOSYMBIOSIS → brown-algal pathway',details:['Why “secondary”? Primary endosymbiosis happened first when a eukaryote engulfed a cyanobacterium. Secondary endosymbiosis happened later when another eukaryote engulfed an entire photosynthetic red alga that already contained that primary plastid.','The simple nested ancestry is: cyanobacterium → chloroplast inside a red alga → red alga engulfed by another eukaryote.','What was kept? Most importantly, the photosynthetic plastid was retained and integrated; some red-algal genes/functions also became incorporated into the host system.','What was lost? Most of the red alga’s independent cellular identity and structures disappeared over evolutionary time; the red-algal nucleus did not remain as a separate nucleus in the lineage relevant to brown algae.','The result was not a red alga living permanently inside a brown alga. It was a newly integrated photosynthetic eukaryotic lineage.','Scientific caution: the exact route by which red-algal-derived plastids reached the ancestors of brown algae is more complex than this teaching diagram and remains debated.']},
{type:'life',date:'Perhaps ~500–200 million years ago (?)',title:'Pathway 3 — brown-algal lineage',summary:'Much later, within the photosynthetic lineage carrying red-algal plastid ancestry, brown algae emerge and diversify.',why:'Brown algae are not plants; complex multicellularity evolved independently along this separate eukaryotic pathway.',uncertainty:'Deep brown-algal divergence dates vary among molecular-clock studies.',flow:'Secondary-endosymbiosis heritage → brown algae → TODAY',details:['Brown algae belong to stramenopiles, a eukaryotic lineage distinct from the green lineage that produced land plants.','Their brown color comes largely from accessory pigments such as fucoxanthin that mask chlorophyll’s green color.','Modern brown algae range from small forms to giant kelps.']},
{type:'life',date:'~470 million years ago',title:'Pathway 2 — land plants',summary:'Descendants of the green algal lineage establish themselves on land.',why:'The chloroplast story now extends from cyanobacteria to green algae and into terrestrial ecosystems.',flow:'Green algal lineage → land plants',details:['Land plants inherited primary plastids through the green lineage.','Early land plants were small and lacked the complex vascular systems of later plants.']},
{type:'life',date:'~430–400 million years ago',title:'Plant evolution — vascular plants',summary:'Plants evolve specialized tissues for moving water and nutrients through the body.',why:'Vascular tissue allows larger, more complex land plants.',flow:'Land plants → vascular plants',details:['Xylem conducts water and minerals; phloem distributes sugars and other organic products.','This innovation supports taller growth and more complex terrestrial vegetation.']},
{type:'life',date:'~360–320 million years ago',title:'Plant evolution — seed plants',summary:'Seeds evolve, protecting and nourishing the developing embryo and allowing reproduction less dependent on free-standing water.',why:'Seeds become one of the major innovations in plant evolution.',flow:'Vascular plants → seed plants',details:['Seeds package an embryo with stored resources and a protective coat.','Seed plants include gymnosperms and, later, flowering plants.']},
{type:'life',date:'~320–300 million years ago',title:'Plant evolution — gymnosperm lineages expand',summary:'Seed plants with exposed (“naked”) seeds diversify, including lineages leading to modern conifers and their relatives.',why:'Gymnosperms dominate many terrestrial environments long before flowering plants become widespread.',flow:'Seed plants → gymnosperms',details:['Living gymnosperms include conifers, cycads, Ginkgo and gnetophytes.','They do not produce flowers or fruits in the angiosperm sense.']},
{type:'life',date:'~140–125 million years ago',title:'Plant evolution — flowering plants',major:true,summary:'Angiosperms appear and rapidly diversify, eventually becoming the dominant plant group in many terrestrial ecosystems.',why:'Flowers and fruits transform plant reproduction and ecological interactions.',flow:'Seed plants → flowering plants → modern flowers',details:['Flowers organize reproductive structures and often facilitate interactions with animal pollinators.','After fertilization, angiosperm ovules become seeds and the ovary typically develops into fruit.','Flowering plants are one late branch of the much older green lineage.']},
{type:'life',date:'~34 million years ago',title:'Pathway 3 — kelps emerge',major:true,summary:'Large brown algae in the kelp lineage appear comparatively late in Earth history.',why:'Kelp is the late outcome of a very old chain: cyanobacterium → chloroplast → red alga → secondary endosymbiosis → brown-algal lineage → kelp.',uncertainty:'The kelp fossil record is sparse; dates remain approximate.',flow:'Brown algae → kelp → modern kelp forests',details:['Kelp are brown algae, not plants.','They independently evolved large, complex multicellular bodies with holdfasts, stipes and blades that can superficially resemble plant structures.','Their plastids ultimately trace back to cyanobacteria through primary and then secondary endosymbiosis.']},
{type:'human',context:true,date:'~800–600 million years ago',title:'Pathway 1 — animals and fungi are established lineages',summary:'Within Opisthokonta, animal and fungal lineages follow separate evolutionary histories.',why:'This is the pathway that eventually provides the animal lineage leading to humans, while fungi continue independently to today.',uncertainty:'Deep divergence dates vary among molecular-clock studies.',flow:'Opisthokont ancestry → fungi → TODAY | animals → TODAY',details:['Animals and fungi are closer relatives to each other than either is to plants.','Fungi are not plants and do not photosynthesize; they obtain nutrients by absorption.','Both animal and fungal lineages remain extraordinarily diverse today.']},
{type:'human',context:true,date:'~8–6 million years ago',title:'Human lineage separates from the chimpanzee/bonobo lineage',summary:'Humans and living chimpanzees/bonobos share an ancestral population; humans did not descend from living chimpanzees.',why:'This begins the very short human-scale portion of the timeline.',details:['The split was a population process, not one instant when a chimpanzee gave birth to a human.','Both descendant lineages continued evolving after their divergence.']},
{type:'human',context:true,date:'~2.8 million years ago',title:'Earliest Homo',summary:'The genus Homo appears in the African fossil record.',why:'Human evolutionary history occupies only a tiny fraction of the timeline.',details:['Homo is one branch within a much larger hominin evolutionary tree with many extinct relatives.']},
{type:'human',context:true,date:'~300,000 years ago',title:'Homo sapiens',major:true,summary:'Our species appears in Africa and later spreads worldwide.',why:'Modern humans arrive extremely late in the history of Earth and life.',details:['Homo sapiens coexisted and interbred with other human lineages, including Neanderthals and Denisovans.']},
{type:'life',date:'TODAY',title:'Life today — ancient lineages still surround us',major:true,summary:'Evolution is a branching tree, not a ladder. Ancient lineages did not simply replace one another; many survived, diversified and coexist today.',why:'The continuing branches make the pivotal endosymbiosis events easier to interpret correctly.',flow:'Bacteria • Archaea • Cyanobacteria • unicellular eukaryotes • red algae • green algae • brown algae/kelp • fungi • plants • animals/humans',branches:[['Bacteria','including modern Cyanobacteria'],['Archaea','including diverse modern archaeal groups'],['Unicellular eukaryotes','many lineages outside our three selected stories'],['Red algae','Pathway 2 continues'],['Green algae','Pathway 2 continues'],['Brown algae / kelp','Pathway 3 continues'],['Fungi','Pathway 1 continues'],['Flowering plants','green-lineage descendants'],['Animals / humans','Pathway 1 continues']],details:['Cyanobacteria contributed to chloroplast ancestry but also continue as free-living bacteria today.','Red algae contributed to secondary endosymbiosis but red algae also continue independently today.','Mitochondria and chloroplasts are organelles inside eukaryotic cells, while their bacterial source lineages also have living relatives today.','The three highlighted pathways are selected teaching stories within a much larger Tree of Life.']},
{type:'human',context:true,date:'Within the last ~12,000 years',title:'Agriculture',summary:'Multiple human societies begin farming and herding, transforming ecosystems.',why:'Cultural change now occurs on timescales far faster than deep biological evolution.',details:['Agriculture arose independently in multiple regions rather than from one single origin.']},
{type:'human',context:true,date:'~5,000 years ago',title:'Writing and recorded history',summary:'Writing systems appear in several early civilizations.',why:'Nearly all written history occupies only a microscopic sliver of the full timeline.',details:['Human history feels long on a cultural scale but is almost instantaneous compared with billions of years of biological evolution.']},
{type:'human',context:true,date:'~250 years ago to today',title:'Industrial age and present day',summary:'Industrialization rapidly increases human influence on Earth systems.',why:'The 13.8-billion-year story reaches the present.',details:['Modern atmospheric oxygen is about 21% by volume.','Human technological change is now occurring far faster than most large-scale evolutionary transitions described above.']}
];

const timeline=document.getElementById('timeline');
const contextToggle=document.getElementById('contextToggle');
const uncertaintyToggle=document.getElementById('uncertaintyToggle');
const expandAll=document.getElementById('expandAll');
let allOpen=false;
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function defaultDetails(e){return [`What happened? ${e.summary}`,`Why it matters: ${e.why||'It marks an important step in the timeline.'}`];}
function render(){
 timeline.innerHTML=events.map((e,i)=>{
   const ds=e.details?.length?e.details:defaultDetails(e);
   const details=`<details class="details" ${allOpen?'open':''}><summary>Learn more</summary><ul>${ds.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`;
   const branches=e.branches?.length?`<div class="branch-grid">${e.branches.map(b=>`<div class="branch"><strong>${esc(b[0])}</strong><br><span>${esc(b[1])}</span></div>`).join('')}</div>`:'';
   return `<article class="event ${e.type} ${e.context?'context':''}" data-index="${i}"><span class="marker" aria-hidden="true"></span><div class="event-card ${e.major?'major':''}"><div class="kicker">${esc(e.type)}</div><h2>${esc(e.title)}</h2><p class="date">${esc(e.date)}</p><p class="summary">${esc(e.summary)}</p>${e.why?`<p class="why"><strong>Why it matters:</strong> ${esc(e.why)}</p>`:''}${e.flow?`<p class="flow">${esc(e.flow)}</p>`:''}${branches}${e.uncertainty?`<p class="uncertainty"><strong>Uncertainty:</strong> ${esc(e.uncertainty)}</p>`:''}${details}</div></article>`;
 }).join('');
}
render();
contextToggle.addEventListener('change',()=>timeline.classList.toggle('context-hidden',!contextToggle.checked));
uncertaintyToggle.addEventListener('change',()=>timeline.classList.toggle('uncertainty-hidden',!uncertaintyToggle.checked));
document.querySelectorAll('.mode').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(b=>b.classList.remove('active'));btn.classList.add('active');timeline.classList.toggle('compact',btn.dataset.mode==='compact');}));
expandAll.addEventListener('click',()=>{allOpen=!allOpen;render();expandAll.textContent=allOpen?'Collapse all Learn More':'Expand all Learn More';});
let deferredPrompt;const installBtn=document.getElementById('installBtn');
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false;});
installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true;});
const refreshApp=document.getElementById('refreshApp');const updateStatus=document.getElementById('updateStatus');
async function refreshToLatest(){refreshApp.disabled=true;const original=refreshApp.textContent;refreshApp.textContent='Checking…';updateStatus.textContent='Checking GitHub for the newest version…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration('./');if(reg){await reg.update();if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});}}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('evolution-timeline-')).map(k=>caches.delete(k)));}updateStatus.textContent='Updating…';const url=new URL(location.href);url.searchParams.set('refresh',Date.now().toString());location.replace(url.toString());}catch(err){updateStatus.textContent='Could not refresh. Check the internet connection and try again.';refreshApp.disabled=false;refreshApp.textContent=original;}}
refreshApp.addEventListener('click',refreshToLatest);
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');if(navigator.onLine)await reg.update();}catch(_){}});}
