const early = [
{kind:'cosmic',context:true,date:'~13.8 Ga',title:'Universe begins',summary:'The Universe begins expanding from an extremely hot, dense early state.',why:'This creates the physical setting from which stars, planets, chemistry and eventually life become possible.',details:['Hydrogen and helium dominate the earliest matter.','Later generations of stars manufacture many heavier elements needed for rocky planets and life.']},
{kind:'cosmic',context:true,date:'~13.6–13.0 Ga',title:'First stars and galaxies',summary:'Stars ignite; stellar fusion and stellar explosions create and disperse heavier elements.',why:'Carbon, oxygen, nitrogen, silicon, iron and other ingredients of planets and life are forged through stellar evolution.',details:['This is the chemical bridge between the early Universe and the material that eventually becomes Earth and living organisms.']},
{kind:'cosmic',context:true,date:'~4.6 Ga',title:'Sun and Solar System form',summary:'A cloud of gas and dust collapses. The Sun forms at the center while the surrounding disk produces planets.',why:'Material inherited from earlier stars becomes organized into our Solar System.',flow:'Solar nebula → Sun + planets',details:['Dust grains collide and grow into planetesimals and eventually planets.','Earth forms in the inner rocky region of this disk.']},
{kind:'earth',context:true,date:'~4.54 Ga',title:'Earth forms',summary:'Rocky material in the inner Solar System accretes into the young Earth.',why:'Earth becomes the planetary setting for the biological story.',details:['Early Earth was geologically violent and chemically very different from the modern planet.']},
{kind:'earth',context:true,date:'~4.5 Ga',title:'Moon forms — giant impact',summary:'The leading model involves a giant impact early in Earth history followed by accretion of orbiting debris.',why:'The Moon becomes a major part of Earth’s long-term planetary history.',details:['In the giant-impact hypothesis, a roughly Mars-sized protoplanet conventionally called Theia collided with the young Earth.','The collision ejected large amounts of hot rocky material into orbit.','Orbiting debris then accreted into the Moon.','Modern versions of the hypothesis differ in collision geometry, mixing and the relative contributions of Earth and impactor material; the exact details remain an active area of research.']},
{kind:'earth',context:true,date:'By ~4.4 Ga',title:'Early crust and liquid water',summary:'Ancient minerals indicate that crust and liquid water existed surprisingly early.',why:'Liquid water provides an important setting for prebiotic chemistry and early life.',details:['Zircon minerals preserve chemical clues that liquid water and differentiated crust existed by this time.']},
{kind:'bacteria',date:'Perhaps ~4.3–4.2 Ga (?)',title:'Origin of life',summary:'Prebiotic chemistry crossed the threshold into evolving biological systems. Exactly how, where and when remains unknown.',why:'This is the beginning of biology, before the last common ancestor of modern cellular life.',uncertainty:'Highly uncertain. The date is shown only to preserve chronological perspective.',details:['What Is Life? Before we can explore the Tree of Life, we first need to answer a simple question: What is life?','A simple scientific definition is: “Life is a self-maintaining system that uses energy, responds to its environment, reproduces, and has the capacity to evolve.”','Scientists do not have one universally accepted definition of life, but they generally agree that all living organisms share a common set of characteristics. A simple way to remember these characteristics is with the mnemonic HORGASM.','H – Homeostasis: Maintains a stable internal environment.','O – Organization: Is composed of one or more cells, the basic units of life.','R – Reproduction: Produces new organisms and passes genetic information to the next generation.','G – Growth: Increases in size and develops throughout its life cycle.','A – Adaptation: Populations evolve over generations, improving their ability to survive and reproduce.','S – Response to Stimuli: Detects and responds to changes in the environment.','M – Metabolism: Obtains, transforms, and uses energy and matter to build, maintain, and power the organism.']},
{kind:'bacteria',date:'Perhaps ~4.25–4.2 Ga (?)',title:'FUCA-type stage (?)',summary:'FUCA is a proposed label for a very early ancestral stage near the emergence of the genetic code and cellular life.',why:'It separates a hypothetical earliest shared biological ancestry from LUCA—the last shared ancestor of living cellular lineages.',uncertainty:'FUCA is hypothetical, not a securely dated organism or fossil.',details:['FUCA means “First Universal Common Ancestor” in this teaching framework.','There may have been a long population-level transition rather than one single first cell.']},
{kind:'bacteria',date:'~4.2 Ga (estimate)',title:'LUCA — Last Universal Common Ancestor',major:true,summary:'The ancestral population from which all cellular life alive today ultimately descends. LUCA was not the first life.',why:'LUCA is the first major anchor for reconstructing the Tree of Life.',flow:'LUCA → Bacteria + Archaea',details:['Likely had DNA and RNA.','Used the universal genetic code, ribosomes and protein synthesis.','Used ATP-based energy metabolism and ion gradients.','Had basic metabolic pathways and reproduction.','Did NOT have a nucleus, mitochondria or chloroplasts.']},
{kind:'bacteria',date:'Perhaps ~4.1–3.5 Ga',title:'The Great Split — Bacteria and Archaea',major:true,summary:'Descendants of the universal ancestral population diverge into the two fundamental domains Bacteria and Archaea.',why:'Both lineages survive to the present, and both later contribute crucial pieces to the eukaryotic story.',uncertainty:'The deepest split is extremely difficult to date; this broad range is for perspective.',flow:'Bacteria → TODAY | Archaea → TODAY',details:['Bacteria commonly have ester-linked membrane lipids and cell walls containing peptidoglycan.','Archaea have ether-linked membrane lipids, lack peptidoglycan, and have information-processing machinery with important similarities to eukaryotes.','Modern bacterial examples include cyanobacteria, E. coli, Bacillus and Streptococcus.','Modern archaeal examples include methanogens, halophiles, thermophiles, ammonia-oxidizers and Asgard archaea.','Two basic cell types: Bacteria and Archaea have prokaryotic cells; members of Eukarya have eukaryotic cells.','Three domains: Bacteria, Archaea and Eukarya.']},
{kind:'bacteria',date:'By ~2.7 Ga; possibly earlier',title:'Cyanobacteria harness sunlight',major:true,summary:'Cyanobacteria use oxygenic photosynthesis: sunlight powers the production of energy-rich organic molecules, with oxygen released as a by-product.',why:'Life begins transforming the entire planet. Cyanobacteria also remain a living bacterial lineage today.',uncertainty:'Oxygenic photosynthesis predates the Great Oxidation Event; its exact origin is uncertain.',flow:'☀ Sunlight → Cyanobacteria → photosynthesis → O₂ waste',details:['Photosynthesis stores captured light energy in chemical bonds.','Using water as an electron donor releases molecular oxygen (O₂).','At first, much of that oxygen reacts with reduced iron, volcanic gases and other oxygen sinks instead of accumulating in the atmosphere.','Cyanobacteria do not disappear later: modern cyanobacteria still exist today.']},
{kind:'earth',date:'~2.45–2.3 Ga',title:'Great Oxidation Event — oxygen changes the planet',major:true,summary:'Oxygen produced biologically begins to persist in the atmosphere and surface environments.',why:'Oxygen is toxic to many anaerobic organisms, but it also creates a powerful new opportunity for aerobic respiration.',flow:'Cyanobacterial O₂ → planetary oxygenation → new metabolic opportunity',details:['Before the GOE, atmospheric O₂ was extremely low compared with today.','Today O₂ is about 21% of the atmosphere.','There is no single secure “peak oxygen percentage” for the GOE; estimates remain debated.']},
{kind:'bacteria',date:'Before ~2.0 Ga',title:'Aerobic respiration exploits oxygen',summary:'Some bacteria use oxygen as the final electron acceptor in respiration, allowing efficient extraction of usable energy from organic molecules.',why:'This metabolic capability sets the stage for the bacterial partner that becomes the mitochondrion.',flow:'Organic molecules + O₂ → efficient ATP production',details:['Life needs usable energy to run metabolism.','Oxygen itself is not “energy”; it enables a highly effective electron-transport process that helps cells make ATP.','The alphaproteobacterial ancestor of mitochondria already possessed aerobic metabolic machinery before becoming an organelle.']},
{kind:'bacteria',date:'~2.37–1.80 Ga (broad estimate)',title:'Mitochondrial endosymbiosis — the energy partnership',major:true,summary:'An archaeal host related to the Asgard lineage forms a permanent partnership with an alphaproteobacterial relative capable of aerobic respiration.',why:'The bacterial partner becomes the MITOCHONDRION—the cell’s major energy-producing organelle, using oxygen to help extract energy from organic molecules and convert ADP + Pi into ATP that powers metabolism.',uncertainty:'The exact date and sequence of eukaryogenesis remain debated.',flow:'Archaeal host + aerobic alphaproteobacterium → MITOCHONDRION',details:['This event occurs after oxygenic photosynthesis and planetary oxygenation, fitting the larger energy story.','Evidence for bacterial ancestry includes mitochondrial DNA, bacterial-type ribosomes, division by fission and a double membrane.','Many mitochondrial genes were later lost or transferred to the host nuclear genome.','Follow the energy: respiration releases stored chemical energy; that energy drives ADP + inorganic phosphate (Pi) → ATP. ATP then powers cellular work and returns to ADP + Pi for recycling.']},
{kind:'bacteria',date:'~1.8–1.6 Ga',title:'LECA — Last Eukaryotic Common Ancestor',major:true,summary:'The last common ancestral population of all living eukaryotic lineages.',why:'By LECA, the complex eukaryotic cell was already established and contained mitochondria.',details:['LECA was not the first eukaryote.','It likely had a nucleus, mitochondria, chromosomes, cytoskeleton, internal membrane systems, vesicle trafficking and mitosis.','Meiosis and sexual reproduction were probably already present.']}
];

const groups = {
animals:{name:'Animals & Fungi',tag:'Animal–Fungi story',intro:'A selected opisthokont story: fungi continue independently, while animals diversify in the sea, later colonize land, and eventually produce humans.',events:[
{date:'Perhaps ~800–600 Ma',title:'Animals and fungi are established lineages',summary:'Animal and fungal lineages are separate branches within Opisthokonta.',why:'Fungi continue independently to today; the animal branch later provides our human perspective.',uncertainty:'Deep divergence dates vary among molecular-clock studies.',details:['Animals and fungi are closer relatives to each other than either is to plants.','Fungi are not plants and do not photosynthesize; they obtain nutrients by absorption.']},
{date:'~635–539 Ma',title:'Marine animals become conspicuous',summary:'Ediacaran ecosystems contain increasingly complex multicellular animals in the oceans.',why:'Animals are established in marine environments long before vertebrates live on land.',details:['The fossil record becomes much more visible in this interval, although animal origins likely predate many familiar fossils.']},
{date:'~539 Ma onward',title:'Cambrian marine diversification',summary:'Many major animal body plans become conspicuous in the marine fossil record.',why:'The early animal story is overwhelmingly an ocean story.',details:['The “Cambrian explosion” does not mean animals appeared instantaneously; it marks a geologically rapid diversification and improved fossil visibility.']},
{date:'~450–430 Ma',title:'Some arthropods colonize land',summary:'Arthropod lineages begin using terrestrial environments after early land vegetation is established.',why:'Land animals do not precede the formation of terrestrial plant-based ecosystems.',details:['The timing differs among arthropod groups and the record is incomplete.']},
{date:'~390–360 Ma',title:'Vertebrates begin the transition onto land',summary:'Tetrapod ancestors evolve from fish-like vertebrates in shallow-water environments and increasingly exploit land.',why:'This occurs long after marine animals and after plants have already transformed terrestrial habitats.',details:['The water-to-land transition was gradual and involved many intermediate forms, not one abrupt move.']},
{date:'~55 Ma',title:'Early primates',summary:'Early primate lineages diversify after the end-Cretaceous extinction.',why:'This provides a compact human perspective without allowing recent history to dominate the app.',details:['Primates are only one very late branch within the much older animal lineage.']},
{date:'~8–6 Ma',title:'Hominin lineage diverges from the chimpanzee/bonobo lineage',summary:'Humans and living chimpanzees/bonobos share an ancestral population; humans did not descend from living chimpanzees.',why:'The human-scale story begins extremely late.',details:['The split was a population process, not one instant when one species suddenly became another.']},
{date:'~2.8 Ma',title:'Earliest Homo',summary:'The genus Homo appears in the African fossil record.',why:'Human evolutionary history occupies only a tiny fraction of the timeline.',details:['Homo is one branch within a much larger hominin tree containing many extinct relatives.']},
{date:'~300 ka',title:'Homo sapiens',major:true,summary:'Our species appears in Africa and later spreads worldwide.',why:'Modern humans arrive almost at the end of the biological timeline.',details:['Homo sapiens coexisted and interbred with other human lineages, including Neanderthals and Denisovans.']}
]},
plastid:{name:'Red / Green Algae & Plants',tag:'Primary-plastid story',intro:'A mitochondria-containing eukaryote acquires a cyanobacterium. The resulting chloroplast lineage later branches into red and green algal histories; the green lineage eventually gives rise to land plants.',events:[
{date:'Perhaps ~1.6–1.0 Ga (?)',title:'Primary endosymbiosis',major:true,summary:'A mitochondria-containing eukaryote engulfs a cyanobacterium and retains it as a permanent photosynthetic partner.',why:'This event produces the PRIMARY PLASTID / CHLOROPLAST ancestor.',uncertainty:'The timing of primary plastid origin remains debated.',flow:'Eukaryote + Cyanobacterium → PRIMARY ENDOSYMBIOSIS → CHLOROPLAST',details:['This is called primary endosymbiosis because the engulfed partner is a bacterium.','Evidence for cyanobacterial ancestry includes plastid DNA, bacterial-type ribosomes, division by fission and a double-membrane heritage.','The host already contained mitochondria; chloroplast acquisition came later.']},
{date:'By ~1.0 Ga (broad estimate)',title:'Red and green algal lineages',major:true,summary:'The primary-plastid lineage diversifies into major branches including red algae and the green lineage.',why:'Red algae and green algae continue independently to the present; neither “turns into” the other.',uncertainty:'Exact divergence dates depend on fossils and molecular-clock assumptions.',flow:'Primary plastid → RED ALGAE → TODAY | GREEN ALGAE → TODAY + land plants',details:['Red algae remain a living lineage today.','Green algae remain a living lineage today.','One green lineage later gives rise to land plants.','A red-algal lineage later contributes to the brown-algal story through secondary endosymbiosis, while red algae themselves continue independently.']},
{date:'~470 Ma',title:'Land plants',major:true,summary:'Descendants of the green algal lineage establish themselves on land.',why:'Plants begin building terrestrial ecosystems before vertebrate animals colonize land.',flow:'Green lineage → land plants',details:['Early land plants were small and lacked the elaborate vascular systems of later plants.','Their presence changes soils, weathering, nutrient cycles and habitats on land.']},
{date:'~430–400 Ma',title:'Vascular plants',summary:'Plants evolve internal conducting tissues that transport water and nutrients.',why:'Vascular tissue supports taller and more complex terrestrial plants.',details:['Xylem and phloem allow plants to move materials internally and support larger body forms.']},
{date:'~360–320 Ma',title:'Seed plants',summary:'Seed-bearing plants evolve, freeing reproduction from some dependence on free-standing water.',why:'Seeds protect embryos and help plants colonize drier terrestrial environments.',details:['Seeds package an embryo with stored resources and protective tissues.']},
{date:'~320–300 Ma',title:'Gymnosperm lineages expand',summary:'Seed plants without flowers diversify extensively.',why:'Gymnosperms dominate many terrestrial environments long before flowering plants become widespread.',details:['Living gymnosperms include conifers, cycads, Ginkgo and gnetophytes.']},
{date:'~140–125 Ma',title:'Flowering plants',major:true,summary:'Angiosperms appear and diversify, eventually becoming dominant in many terrestrial ecosystems.',why:'Flowers and fruits transform plant reproduction and ecological interactions.',flow:'Green algae → land plants → vascular plants → seeds → flowering plants',details:['Flowers organize reproductive structures and often facilitate interactions with animal pollinators.','After fertilization, angiosperm ovules become seeds and the ovary typically develops into fruit.']}
]},
brown:{name:'Brown Algae & Kelp',tag:'Secondary-endosymbiosis story',intro:'A red alga from the primary-plastid story contributes to another eukaryotic lineage. That photosynthetic inheritance eventually becomes part of the brown-algal lineage; kelp appears much later.',events:[
{date:'Perhaps ~1.2–0.8 Ga (?)',title:'Secondary endosymbiosis involving a red alga',major:true,summary:'Another eukaryotic host engulfs a photosynthetic red alga that already contains a cyanobacterium-derived plastid.',why:'The red-algal photosynthetic machinery becomes integrated into a different eukaryotic lineage; the red-algal lineage itself continues independently.',uncertainty:'The exact evolutionary route and timing of red-derived plastids among these ancient lineages remain debated.',flow:'Red alga from primary-plastid story + another eukaryote → SECONDARY ENDOSYMBIOSIS',details:['Why “secondary”? The first endosymbiosis was a eukaryote engulfing a cyanobacterium. The second involves a eukaryote engulfing an already-photosynthetic eukaryote.','Most of the engulfed red alga’s independent cellular identity was eventually lost.','Its photosynthetic plastid was retained, while many genes were lost or transferred to the host genome.','In the lineage relevant to brown algae, the red-algal nucleus itself was not retained as an independent nucleus.','The exact route by which red-algal-derived plastids reached brown-algal ancestors may have involved additional transfers or losses; the main timeline shows the big-picture relationship.']},
{date:'Perhaps ~500–200 Ma (?)',title:'Brown-algal lineage develops and diversifies',summary:'Within the photosynthetic stramenopile radiation, the lineage leading to brown algae becomes distinct and later diversifies.',why:'Brown algae are a separate eukaryotic lineage from green plants despite also performing photosynthesis.',uncertainty:'Deep brown-algal divergence dates vary among studies and the fossil record is incomplete.',details:['Brown algae belong to stramenopiles, not to the green plant lineage.','Their photosynthetic plastids ultimately trace back through a red-algal intermediary to cyanobacteria.']},
{date:'~34 Ma',title:'Kelp emerges',major:true,summary:'Large brown algae in the kelp lineage appear comparatively late in Earth history.',why:'Kelp is the late outcome of a very old chain: cyanobacterium → chloroplast → red alga → secondary endosymbiosis → brown-algal lineage → kelp.',uncertainty:'The kelp fossil record is sparse; dates remain approximate.',flow:'Brown algae → KELP → modern kelp forests',details:['Kelp are brown algae, not plants.','They independently evolved large, complex multicellular bodies with holdfasts, stipes and blades that can superficially resemble plant structures.','Their plastids ultimately trace back to cyanobacteria through primary and then secondary endosymbiosis.']}
]}
};


const earthDayRows = [
['Earth forms','4.54 Ga','12:00:00 AM','0.00%'],
['Moon forms','~4.50 Ga','12:12:41 AM','0.88%'],
['Early crust & liquid water','~4.40 Ga','12:44:24 AM','3.08%'],
['Origin of life (?)','perhaps ~4.25 Ga','1:31:59 AM','6.39%'],
['FUCA-type stage (?)','perhaps ~4.22 Ga','1:41:30 AM','7.05%'],
['LUCA','~4.20 Ga','1:47:50 AM','7.49%'],
['Great split — Bacteria / Archaea','perhaps ~3.80 Ga','3:54:43 AM','16.30%'],
['Cyanobacterial photosynthesis','~2.70 Ga','9:43:37 AM','40.53%'],
['Great Oxidation Event','~2.40 Ga','11:18:46 AM','47.14%'],
['Mitochondrial endosymbiosis','representative ~2.00 Ga','1:25:38 PM','55.95%'],
['LECA','~1.70 Ga','3:00:48 PM','62.56%'],
['Primary plastid / chloroplast','representative ~1.30 Ga','5:07:40 PM','71.37%'],
['Red & green algal lineages','~1.00 Ga','6:42:49 PM','77.97%'],
['Secondary endosymbiosis','representative ~1.00 Ga','6:42:49 PM','77.97%'],
['Marine animals / Ediacaran','~600 Ma','8:49:42 PM','86.78%'],
['Cambrian begins','~539 Ma','9:09:02 PM','88.13%'],
['Land plants','~470 Ma','9:30:56 PM','89.65%'],
['Early terrestrial arthropods','~440 Ma','9:40:26 PM','90.31%'],
['Vascular plants','~425 Ma','9:45:12 PM','90.64%'],
['Tetrapod transition toward land','~370 Ma','10:02:39 PM','91.85%'],
['Seed plants','~350 Ma','10:08:59 PM','92.29%'],
['Flowering plants','~130 Ma','11:18:46 PM','97.14%'],
['Primates','~55 Ma','11:42:33 PM','98.79%'],
['Kelp','~34 Ma','11:49:13 PM','99.25%'],
['Hominins','~7 Ma','11:57:47 PM','99.85%'],
['Earliest Homo','~2.8 Ma','11:59:07 PM','99.94%'],
['Homo sapiens','~300 ka','11:59:54 PM','99.993%'],
['Agriculture','~12 ka','11:59:59.77 PM','99.99974%'],
['Writing','~5 ka','11:59:59.90 PM','99.99989%'],
['Industrial Revolution','~250 years ago','11:59:59.995 PM','99.999994%'],
['Today','0','12:00:00 AM','100%']
];

function earthDayHtml(){
 return `<section class="earth-day"><div class="earth-day-head"><div><p class="eyebrow">Deep-time perspective</p><h2>🌎 Earth’s History in One Day</h2><p>If Earth’s 4.54-billion-year history is compressed into 24 hours, Earth forms at <strong>12:00 AM</strong> and TODAY arrives at <strong>12:00 AM the next day</strong>. The percentage shows how much of Earth history has elapsed when each milestone occurs.</p></div><div class="earth-day-clock">24 HOURS<br><strong>4.54 BILLION YEARS</strong></div></div><div class="earth-day-table" role="table" aria-label="Earth history compressed into 24 hours"><div class="earth-day-row earth-day-header" role="row"><div>Milestone</div><div>Real date</div><div>24-hour clock</div><div>Earth history elapsed</div></div>${earthDayRows.map(r=>`<div class="earth-day-row" role="row"><div class="earth-day-event">${esc(r[0])}</div><div data-label="Real date">${esc(r[1])}</div><div data-label="Clock"><strong>${esc(r[2])}</strong></div><div data-label="Elapsed"><strong>${esc(r[3])}</strong></div></div>`).join('')}</div><div class="earth-day-takeaway"><strong>Perspective:</strong> LUCA appears before 2 AM, oxygenation occurs before noon, mitochondria arrive in the early afternoon, chloroplasts around 5 PM, land plants around 9:31 PM, kelp around 11:49 PM, and <strong>Homo sapiens appears only about six seconds before midnight.</strong></div>${detailsHtml(['The clock times are mathematical conversions of the representative dates shown; they are not independent scientific date estimates.','For uncertain events such as the Great Split, mitochondrial endosymbiosis, primary plastid acquisition and secondary endosymbiosis, a representative point within the broad teaching range is used only to place the event on the 24-hour clock.','Calculation: percentage elapsed = (Earth age − years before present) ÷ Earth age × 100. Clock time = that fraction × 24 hours.','This compressed-day view counters a visual bias of long timelines: familiar modern events can occupy lots of screen space even though they occur extremely late in Earth history.'])}</section>`;
}

const otherDetails=['Eukaryotes diversified into many more lineages than the three teaching stories emphasized here.','Modern single-celled eukaryotes include amoebae, ciliates, dinoflagellates, diatoms, many flagellates and yeasts.','Choanoflagellates are especially useful because they are close living unicellular relatives of animals.','The presence of these lineages reminds us that evolution is a branching tree, not a ladder.'];

const timeRows = [
['~13.8 Ga','Universe begins','cosmic'],['~4.6 Ga','Sun & Solar System','cosmic'],['~4.54 Ga','Earth forms','earth'],['~4.5 Ga','Moon giant impact','earth'],['Perhaps ~4.3–4.2 Ga','Origin of life (?)','bacteria'],['~4.2 Ga','LUCA','bacteria'],['Perhaps ~4.1–3.5 Ga','Bacteria / Archaea split','bacteria'],['By ~2.7 Ga','Cyanobacterial photosynthesis','bacteria'],['~2.45–2.3 Ga','Great Oxidation Event','earth'],['~2.37–1.80 Ga','Mitochondrial endosymbiosis','bacteria'],['~1.8–1.6 Ga','LECA','bacteria'],['Perhaps ~1.6–1.0 Ga','Primary endosymbiosis → chloroplast','plastid'],['By ~1.0 Ga','Red & green algal lineages','plastid'],['Perhaps ~1.2–0.8 Ga','Secondary endosymbiosis (red alga)','brown'],['~635–539 Ma','Marine animals prominent','animals'],['~539 Ma onward','Cambrian marine diversification','animals'],['~470 Ma','Land plants','plastid'],['~450–430 Ma','Early terrestrial arthropods','animals'],['~430–400 Ma','Vascular plants','plastid'],['~390–360 Ma','Vertebrate transition toward land','animals'],['~360–320 Ma','Seed plants','plastid'],['~320–300 Ma','Gymnosperms expand','plastid'],['Perhaps ~500–200 Ma','Brown-algal lineage diversifies','brown'],['~140–125 Ma','Flowering plants','plastid'],['~55 Ma','Early primates','human'],['~34 Ma','Kelp','brown'],['~8–6 Ma','Hominin split','human'],['~2.8 Ma','Earliest Homo','human'],['~300 ka','Homo sapiens','human'],['TODAY','Modern bacteria, archaea, algae, fungi, plants, animals & unicellular eukaryotes','bacteria']
];

const storyView=document.getElementById('storyView');const timeView=document.getElementById('timeView');const contextToggle=document.getElementById('contextToggle');const uncertaintyToggle=document.getElementById('uncertaintyToggle');const expandAll=document.getElementById('expandAll');let allOpen=false;
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function detailsHtml(list){return `<details class="details" ${allOpen?'open':''}><summary>Learn More</summary><ul>${list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`}
function card(e,extra=''){const cls=`event-card ${e.major?'major':''} ${extra}`;return `<article class="${cls} ${e.context?'context':''}"><h3>${esc(e.title)}</h3><p class="date">${esc(e.date)}</p><p class="summary">${esc(e.summary)}</p>${e.why?`<p class="why"><strong>Why it matters:</strong> ${esc(e.why)}</p>`:''}${e.flow?`<p class="flow">${esc(e.flow)}</p>`:''}${e.uncertainty?`<p class="uncertainty"><strong>Uncertainty:</strong> ${esc(e.uncertainty)}</p>`:''}${detailsHtml(e.details||[`What happened? ${e.summary}`])}</article>`}
function renderStory(){
 const earlyHtml=early.map(e=>card(e,`${e.kind}-event`)).join('');
 const groupSection=(key)=>{const g=groups[key];return `<details class="section-shell story-accordion ${key}-shell" open><summary class="story-summary"><span><strong>${esc(g.name)}</strong><small>${esc(g.tag)}</small></span><span class="story-arrow">⌄</span></summary><div class="story-body"><p class="story-intro">${esc(g.intro)}</p><div class="event-list">${g.events.map(e=>card(e)).join('')}</div></div></details>`};
 storyView.innerHTML=`<section class="section-shell spine"><div class="section-head"><div><h2>Part I — Energy, planet and the rise of eukaryotes</h2><p>The main spine: sunlight → oxygen → aerobic respiration → mitochondrion → LECA.</p></div><span class="thread-tag bacteria">Core spine</span></div><div class="event-list">${earlyHtml}</div></section>
 <div class="tree-roadmap"><h2>The Tree expands — selected lineages we will follow</h2><p class="roadmap-intro">Eukaryotes diversify into many lineages. These are four organized threads for teaching—not the only branches of the eukaryotic tree.</p><div class="roadmap-grid"><div class="road plastid"><h3>Red / Green Algae & Plants</h3><p>Primary endosymbiosis → chloroplast → red algae + green algae → land plants → flowers.</p></div><div class="road brown"><h3>Brown Algae & Kelp</h3><p>Red-algal contribution → secondary endosymbiosis → brown algae → much later kelp.</p></div><div class="road animals"><h3>Animals & Fungi</h3><p>Fungi continue independently; animals diversify in the sea, later move onto land, and much later give rise to humans.</p></div><div class="road other"><h3>Other Eukaryotes</h3><p>Many unicellular and other eukaryotic lineages continue independently → TODAY.</p></div></div><div class="crossover">Important crossover: <strong>Red algae stay in the primary-plastid thread and continue to TODAY.</strong> A red-algal lineage also contributes sideways to the brown-algal thread through secondary endosymbiosis.</div>${detailsHtml(['This roadmap organizes the story by group so an audience does not lose track of which lineage is being followed.','The Strict Time Map provides the second coordinate: when these events occurred relative to each other.','A source lineage can continue independently even when one descendant participates in endosymbiosis. Cyanobacteria and red algae are key examples.'])}</div>
 <div class="organelle-banner"><strong>☀️ CHLOROPLAST STORY BEGINS AFTER LECA</strong><br><span>A mitochondria-containing eukaryote later acquires cyanobacterial photosynthesis.</span></div>
 <div class="group-grid">${groupSection('plastid')}${groupSection('brown')}${groupSection('animals')}<section class="section-shell other-shell"><div class="section-head"><div><h2>Other Eukaryotic Lineages</h2><p>Many lineages outside the three focal stories remain important and continue to the present.</p></div><span class="thread-tag bacteria">Other lineages</span></div>${detailsHtml(otherDetails)}</section></div>
 ${earthDayHtml()}
 <section class="energy-summary"><h2>⚡ Follow the Energy — the story in one flow</h2><div class="energy-flow"><div><strong>Life needs energy</strong><span>↓</span><b>☀️ Sunlight</b><span>↓</span><b>Photosynthesis captures energy</b><span>↓</span><b>Energy stored in organic molecules + O₂ released</b><span>↓</span><b>🌎 Oxygen changes Earth</b><span>↓</span><b>Aerobic respiration exploits O₂</b><span>↓</span><b>⚡ MITOCHONDRION</b><span>↓</span><b>ADP + Pi + energy → ATP</b><span>↓</span><b>ATP powers metabolism</b><span>↓</span><b>☀️ CHLOROPLAST</b><span>↓</span><b>Red & green algal lineages</b><span>↓</span><b>Different histories → plants and kelp</b></div></div><p class="energy-conclusion"><strong>Follow the energy:</strong> life evolves ways to capture energy, store it, release it and convert it into forms that power metabolism. Those innovations changed both life and the planet.</p>${detailsHtml(['Photosynthesis captures external solar energy and stores it as chemical energy in organic molecules.','Respiration releases part of that stored chemical energy and uses it to drive ADP + inorganic phosphate (Pi) → ATP.','ATP is immediately usable by the cell for metabolic work; when ATP is used, it returns to ADP + Pi and can be recharged.','The mitochondrial story emphasizes release and conversion of stored chemical energy; the chloroplast story emphasizes capture and storage of solar energy.'])}</section>
 <section class="payoff"><h2>Why kelp is not a plant</h2><div class="compare"><div><h3>🌼 Plant route</h3><p>Cyanobacterium → primary endosymbiosis → chloroplast → <strong>green lineage</strong> → land plants → flowering plants.</p></div><div><h3>🌿 Kelp route</h3><p>Cyanobacterium → primary plastid → <strong>red-algal lineage</strong> → secondary endosymbiosis → brown-algal lineage → kelp.</p></div></div>${detailsHtml(['Plants and kelp both photosynthesize, and both ultimately trace plastid ancestry to cyanobacteria.','They are nevertheless members of different eukaryotic lineages with different evolutionary histories.','The visual similarity of kelp blades, stipes and holdfasts to plant leaves, stems and roots reflects convergent solutions, not close plant ancestry.'])}</section>`;
 applyVisibility();
}
function renderTime(){timeView.innerHTML=`<section class="time-map"><h2>Strict Time Map — all threads on one clock</h2><p class="time-intro">This view deliberately ignores grouping. Older events are above younger events, so marine animals, land plants, land animals, flowers, kelp and humans can be compared directly.</p><div class="time-rows">${timeRows.map(r=>`<div class="time-row ${r[2]}"><div class="time-date">${esc(r[0])}</div><div class="time-mark"></div><div class="time-label"><strong>${esc(r[1])}</strong><span class="time-badge">${esc(r[2])}</span></div></div>`).join('')}</div></section>`}
function applyVisibility(){storyView.classList.toggle('context-hidden',!contextToggle.checked);storyView.classList.toggle('uncertainty-hidden',!uncertaintyToggle.checked)}
renderStory();renderTime();
function configureStoryAccordions(){const stories=[...storyView.querySelectorAll('.story-accordion')];const mobile=window.matchMedia('(max-width:820px)').matches;if(mobile){stories.forEach(d=>d.removeAttribute('open'));stories.forEach(d=>d.addEventListener('toggle',()=>{if(!d.open)return;stories.forEach(o=>{if(o!==d)o.removeAttribute('open')})},{once:false}))}else{stories.forEach(d=>d.setAttribute('open',''))}}
configureStoryAccordions();
contextToggle.addEventListener('change',applyVisibility);uncertaintyToggle.addEventListener('change',applyVisibility);
document.querySelectorAll('.mode').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const isStory=btn.dataset.view==='story';storyView.hidden=!isStory;timeView.hidden=isStory;}));
expandAll.addEventListener('click',()=>{allOpen=!allOpen;renderStory();configureStoryAccordions();expandAll.textContent=allOpen?'Collapse all Learn More':'Expand all Learn More';});
let deferredPrompt;const installBtn=document.getElementById('installBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});
const refreshApp=document.getElementById('refreshApp');const updateStatus=document.getElementById('updateStatus');async function refreshToLatest(){refreshApp.disabled=true;refreshApp.textContent='Checking…';updateStatus.textContent='Checking GitHub for the newest version…';try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration('./');if(reg){await reg.update();if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})}}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('evolution-timeline-')).map(k=>caches.delete(k)))}const url=new URL(location.href);url.searchParams.set('refresh',Date.now().toString());location.replace(url.toString())}catch(err){updateStatus.textContent='Could not refresh. Check the internet connection and try again.';refreshApp.disabled=false;refreshApp.textContent='Refresh / Check for Updates'}}refreshApp.addEventListener('click',refreshToLatest);
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');if(navigator.onLine)await reg.update()}catch(_){}})}
